name: Deploy static content to Pages

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Packages
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: teamhelper-community/teamhelper-community.github.io
          target_branch: master
          build_dir: .vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_TOKEN }}